version: '3.8'

services:  
  postgres:
    container_name: identity-api-postgres-dev
    image: postgres:latest
    hostname: localhost
    ports:
        - 5432:5432
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
